
//Nav Reducer
export const CHANGE_NAVIGATION='CHANGE_NAVIGATION';

//Register Reducer
export const CHANGE_REGISTER_EMAIL="CHANGE_REGISTER_EMAIL";
export const CHANGE_REGISTER_PASS="CHANGE_REGISTER_PASS";
export const CHANGE_REGISTER_CONFIRM="CHANGE_REGISTER_CONFIRM";
export const CHANGE_REGISTER_USERNAME="CHANGE_REGISTER_USERNAME";
export const CHANGE_REGISTER_NAME="CHANGE_REGISTER_NAME";
export const CHANGE_REGISTER_BIRTHDAY="CHANGE_REGISTER_BIRTHDAY";
export const CHANGE_REGISTER_JOINED="CHANGE_REGISTER_JOINED";
export const RESET_REGISTER="RESET_REGISTER";



export const CHANGE_NAME='CHANGE_NAME';
export const CHANGE_ONLINE_STATUS='CHANGE_ONLINE_STATUS';
